# Generated by Django 5.1.3 on 2024-11-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='good_for',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
